# Fill in your real values below. 
# NOTE: This is an ESP32 board and is only capable of running on 2.4GHz WiFi bands.

# WiFi credentials
CIRCUITPY_WIFI_SSID = [MY_WIFI_NOT_YOURS]
CIRCUITPY_WIFI_PASSWORD = [WIFI_PASSWORD]

# Adafruit credentials
ADAFRUIT_AIO_USERNAME = [MY_USERNAME]
ADAFRUIT_AIO_KEY = [MY_AIO_KEY]


# Avoiding out of memory crash for CircuitPython
CIRCUITPY_PYSTACK_SIZE = 3072